<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>IxiOfflineTools</AssemblyTitle>
    <Product>IxiOfflineTools</Product>
    <Copyright>Copyright ©  2021</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;DEBUG;LW_BUILD</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
    <DefineConstants>TRACE;LW_BUILD</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentCommandLineParser" Version="1.4.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Open.NAT" Version="2.1.0.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.10" />
    <PackageReference Include="sqlite-net-pcl" Version="1.6.292" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.core" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.linux" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.osx" Version="1.1.14" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.v110_xp" Version="1.1.14" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
  </ItemGroup>
  <Import Project="..\..\Ixian-Core\IXICore.projitems" Label="Shared" />
</Project>